version: "3.2"
services:
  php:
    build:
      context: .
    networks:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html/
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: criminal-cases-server
networks:
  backend:
